version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    command: ["wait-for-it", "mysql:3306", "--", "/usr/local/bin/run.sh"]
    ports:
      - ${DOCKER_WEB_PORT}:80
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
